#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM artifactorycloud.ual.com/l-docker-releases/datadog/dotnet/aspnet:6.0.5-2.10.0 AS base


WORKDIR /app
EXPOSE 80

FROM artifactorycloud.ual.com/l-docker/ms/dotnet/core/sdk:6.0 AS build
WORKDIR /

COPY ["src/Services/MSCPayment/ETC/United.Mobile.ETC.Api/United.Mobile.ETC.Api.csproj", "src/Services/MSCPayment/ETC/United.Mobile.ETC.Api/"]
COPY ["src/Services/MSCPayment/ETC/United.Mobile.ETC.Business/United.Mobile.ETC.Business.csproj", "src/Services/MSCPayment/ETC/United.Mobile.ETC.Business/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.Common/United.Mobile.DataAccess.Common.csproj", "src/DataAccess/United.Mobile.DataAccess.Common/"]
COPY ["src/Core/United.Utility/United.Utility.csproj", "src/Core/United.Utility/"]
COPY ["src/Core/United.Ebs.Logging/United.Ebs.Logging.csproj", "src/Core/United.Ebs.Logging/"]
COPY ["src/Models/United.Mobile.Model.Common/United.Mobile.Model.Common.csproj", "src/Models/United.Mobile.Model.Common/"]
COPY ["src/Core/United.Common.Helper/United.Common.Helper.csproj", "src/Core/United.Common.Helper/"]
COPY ["src/DataAccess/Ancillary/United.Mobile.DataAccess.Ancillary/United.Mobile.DataAccess.Product.csproj", "src/DataAccess/Ancillary/United.Mobile.DataAccess.Ancillary/"]
COPY ["src/Models/United.Mobile.Model.MSC/United.Mobile.Model.MSC.csproj", "src/Models/United.Mobile.Model.MSC/"]
COPY ["src/DataAccess/United.Mobile.DataAccess.DynamoDB/United.Mobile.DataAccess.DynamoDB.csproj", "src/DataAccess/United.Mobile.DataAccess.DynamoDB/"]
COPY ["src/Core/Common/United.Common.Helper.MSCPayment/United.Common.Helper.MSCPayment.csproj", "src/Core/Common/United.Common.Helper.MSCPayment/"]
COPY ["src/DataAccess/United.DataAccess.MerchandizeService/United.DataAccess.MerchandizeService.csproj", "src/DataAccess/United.DataAccess.MerchandizeService/"]
COPY ["src/DataAccess/MSCPayment/United.Mobile.DataAccess.MSCPayment/United.Mobile.DataAccess.MSCPayment.csproj", "src/DataAccess/MSCPayment/United.Mobile.DataAccess.MSCPayment/"]

ARG NUGET_PASSWORD
ARG NUGET_USERNAME


RUN dotnet nuget add source https://artifactorycloud.ual.com/artifactory/api/nuget/v3/v-nuget \
            -n artifactory \
            -u ${NUGET_USERNAME}  \
            -p ${NUGET_PASSWORD} \
            --store-password-in-clear-text


COPY . .
WORKDIR "/src/Services/MSCPayment/ETC/United.Mobile.ETC.Api"

FROM build AS publish
ARG VERSION
RUN dotnet build "United.Mobile.ETC.Api.csproj" -c Debug -r linux-x64
RUN mkdir VC/
RUN cp -f -r bin/Debug/net6.0/linux-x64/* VC
RUN pwsh -Command Invoke-Command -ScriptBlock "{Compress-Archive -Path "VC/*" -DestinationPath "VC/${VERSION}.zip"}"

FROM artifactorycloud.ual.com/v-docker/btw/harness/images/veracode-powershell-java-alpine:latest AS release
ARG VERSION
ARG VERACODE_ID
ARG VERACODE_KEY
ARG APPNAME
ARG PURPOSE
COPY --from=publish /src/Services/MSCPayment/ETC/United.Mobile.ETC.Api/VC/${VERSION}.zip . 
COPY --from=build /devops-utilities/veracode-execute.ps1 .  
RUN /opt/microsoft/powershell/7/pwsh ./veracode-execute.ps1 ${VERACODE_ID} ${VERACODE_KEY} ${APPNAME} ${VERSION} ${VERSION}.zip ${PURPOSE}